- name: Install the package "nginx"
  ansible.builtin.apt:
    name: nginx

- name: Install nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Copy files to the remote machine
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx
    - Restart Nginx-exporter

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
