- name: Install the package "nginx"
  ansible.builtin.apt:
    name: nginx

- name: Install nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Copy files to the remote machine
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx
    - Restart Nginx-exporter

- name: Nginx services
  ansible.builtin.service:
    name: "{{item}}" 
    state: started
    enabled: true
  loop: 
    - nginx
    - prometheus-nginx-exporter

- name: Copy files to the remote machine
  ansible.builtin.template:
    src: size.conf.j2
    dest: /etc/nginx/conf.d/size.conf
  notify:
    - Restart Nginx
    - Restart Nginx-exporter
  when: inventory_hostname in groups['grafana']

#- name: Nginx service
#  ansible.builtin.service:
#    name: nginx
#    state: started
#    enabled: true
#
#- name: Nginx exporter
#  ansible.builtin.service:
#    name: prometheus-nginx-exporter
#    state: started
#    enabled: true
