- name: Install the package "nginx"
  ansible.builtin.apt:
    name: nginx

- name: Copy files to the remote machine
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
