- name: Grafana directory
  ansible.builtin.file:
    name: "/opt/grafana/provisioning/{{ item }}"
    state: directory
  loop:
    - dashboards
    - datasources
  notify: Restart Grafana

- name: Grafana configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true
  notify: Restart Grafana

- name: Grafana dashboard
  ansible.builtin.template:
    src: dashboard.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart Grafana

- name: Grafana datasource
  ansible.builtin.template:
    src: datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasource.yaml
  notify: Restart Grafana

- name: Grafana provisioning
  ansible.builtin.copy:
    dest: "/opt/grafana/provisioning/dashboards/{{item}}"
    src: "{{item}}"
  loop:
    - influxdb.json
    - main.json
    - mysql.json
    - syslog.json
  notify: Restart Grafana

- name: Grafana Docker container
  community.docker.docker_container: 
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
    restart_policy: always
