- name: Create Agama directory
  file:
    name: /opt/agama
    state: directory

- name: Download AGAMA application and Dockerfile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama
  loop:
    - agama.py
    - Dockerfile

- name: Build Docker image for Agama
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Start Docker container for Agama
  docker_container:
    name: agama
    image: agama
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    ports:
      - "{{agama_port}}:8000"
  no_log: true  