- name: Create Agama directory
  file:
    name: /opt/agama
    state: directory

- name: Download AGAMA application and Dockerfile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama
  loop:
    - agama.py
    - Dockerfile

- name: Build Docker image for Agama
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Start Docker container for Agama
  docker_container:
    name: agama-{{ item|int +1}}
    image: agama
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@mysql-2/{{ mysql_database }}"
    ports:
      - "{{agama_port + item|int}}:8000"
    state: started
  no_log: true  
  loop: "{{ range(agama_amount) | list }}"

# - name: Get information about all Agama containers
#   docker_container_info:
#     name: "agama-*"
#   register: agama_containers_info

# - name: Extract container names and count from the results
#   set_fact:
#     agama_container_names: "{{ agama_containers_info.containers | map(attribute='Name') | list }}"
#     agama_container_count: "{{ agama_containers_info.containers | default([]) | length }}"



# - name: Print Agama container names to console
#   debug:
#     var: agama_container_names
