- name: Restart daemon service
  systemd:
    state: restarted
    daemon_reload: true
    name: keepalived-exporter

- name: Restart Keepalived
  service: 
    name: keepalived
    state: restarted

