- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server

- name: Install python library
  ansible.builtin.apt:
    name: python3-pymysql

- name: mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Copy override to the remote host
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock


