- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Restart MySQL exporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: restarted

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    primary_host: "mysql-2"
    primary_user: "{{ mysql_replication_user }}"
    primary_password: "{{ mysql_replication_password }}"
  loop:
    - stopreplica
    - changeprimary
    - resetprimary
    - startreplica
  when: inventory_hostname != mysql_host
