- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Restart MySQL exporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: restarted
