#- name: Add the user 'juri' with the home directory
#  ansible.builtin.user:
#    name: juri
#    state: present
#    createhome: yes
#
#- name: Add the user 'roman' with the home directory
#  ansible.builtin.user:
#    name: roman
#    createhome: true
#    home: "/home/roman"
#
#- name: Set authorized key for 'juri'
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys
#
#- name: Set authorized key for 'roman'
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install prometheus-node-exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter

- name: Prometheus-node-exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Install ca-certificates
  ansible.builtin.apt:
    name: ca-certificates=20230311ubuntu0.20.04.1

#- name: Ping my hosts
#  ansible.builtin.ping:

#- name: Print message
#  ansible.builtin.debug:
#  msg: Hello world

- name: Install rsyslog
  ansible.builtin.apt:
    name: rsyslog

- name: Configuration for rsyslog
  ansible.builtin.template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: Start rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true